project:
  type: website
  output-dir: docs
  resources: 
    - CNAME
    - .nojekyll
    - "!posts/gepa-deepdive/.git"
    - "!posts/gepa-deepdive/.gitignore"

website:
  google-analytics: "G-EMRH6XWVFQ"
  description: "A blog about tech, programming, and life."
  site-url: https://risheekkumar.in # you must change this appropriately for RSS feeds to work properly
  title: "Risheekkumar Baskaran"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/risheekkumar-baskaran-748115120/
      - icon: github
        href: https://github.com/risheekkumarb
      - icon: twitter
        href: https://x.com/BRisheek
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: auto
  


